# Generated by Django 4.2.6 on 2023-11-08 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoCajas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre de caja')),
                ('estado_global', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default=('cerrado', 'Cerrado'), max_length=7, verbose_name='Estado global')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto de caja')),
            ],
            options={
                'verbose_name': 'Catalogo de cajas',
                'verbose_name_plural': 'Catalogo cajas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto inicial')),
                ('monto_vendido', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto vendido')),
                ('fecha_hora_abrio', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_cerro', models.DateTimeField(blank=True, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cashiers.catalogocajas', verbose_name='Tipo de caja')),
                ('vendedor_abrio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Último vendedor')),
            ],
            options={
                'verbose_name': 'MovimientoCaja',
                'verbose_name_plural': 'MovimientoCajas',
            },
        ),
    ]
