# Generated by Django 4.2.6 on 2023-11-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashiers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CatalogoCajas',
            new_name='CatalogoCaja',
        ),
        migrations.AlterModelOptions(
            name='catalogocaja',
            options={'ordering': ['id'], 'verbose_name': 'Catalogo de caja', 'verbose_name_plural': 'Catalogo cajas'},
        ),
    ]
