# Generated by Django 4.2.6 on 2023-11-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashiers', '0004_alter_movimientocaja_monto_cierre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='monto_apertura',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Monto inicial'),
        ),
    ]
