# Generated by Django 4.2.6 on 2023-11-10 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_departamento_unidadmedida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['id'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={'ordering': ['id'], 'verbose_name': 'Unidad de medida', 'verbose_name_plural': 'Unidades de medida'},
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True, unique=True, verbose_name='producto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario')),
                ('existencia', models.IntegerField(blank=True, null=True, verbose_name='existencia')),
                ('existencia_minima', models.IntegerField(blank=True, null=True, verbose_name='existencia minima')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.departamento', verbose_name='departamento')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.marca', verbose_name='marca')),
                ('unidades', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.unidadmedida', verbose_name='unidad de medida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
    ]
