# Generated by Django 4.2.6 on 2023-11-10 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='unidad',
            new_name='nombre',
        ),
    ]
