# Generated by Django 4.2.6 on 2023-11-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(blank=True, choices=[('Persona Física', 'Persona Física'), ('Persona Moral', 'Persona Moral'), ('Sociedad Anónima', 'Sociedad Anónima'), ('Sociedad de Responsabilidad Limitada', 'Sociedad de Responsabilidad Limitada'), ('Asociación Civil', 'Asociación Civil'), ('Sociedad en Nombre Colectivo', 'Sociedad en Nombre Colectivo'), ('Sociedad en Comandita Simple', 'Sociedad en Comandita Simple'), ('Sociedad en Comandita por Acciones', 'Sociedad en Comandita por Acciones'), ('Sociedad Cooperativa', 'Sociedad Cooperativa'), ('Sociedad de Capital Variable', 'Sociedad de Capital Variable')], max_length=36, null=True, verbose_name='Razón social'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='R.F.C.'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Teléfono'),
        ),
    ]
