# Generated by Django 4.2.6 on 2023-11-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de venta'),
        ),
    ]
