# Generated by Django 4.2.6 on 2023-11-17 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashiers', '0005_alter_movimientocaja_monto_apertura'),
        ('sales', '0005_alter_venta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='monto recibido'),
        ),
        migrations.AddField(
            model_name='venta',
            name='movimiento_caja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cashiers.movimientocaja', verbose_name='movimiento de caja'),
        ),
        migrations.AddField(
            model_name='venta',
            name='vuelto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='vuelto dado'),
        ),
    ]
