# Generated by Django 4.2.6 on 2023-11-17 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashiers', '0005_alter_movimientocaja_monto_apertura'),
        ('sales', '0007_alter_venta_movimiento_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='movimiento_caja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cashiers.movimientocaja', verbose_name='movimiento de caja'),
        ),
    ]
