# Generated by Django 4.2.6 on 2023-11-17 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashiers', '0005_alter_movimientocaja_monto_apertura'),
        ('sales', '0009_alter_venta_cliente_alter_venta_descuento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='cliente',
            new_name='clienteS',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='descuento',
            new_name='descuentoS',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='fecha',
            new_name='fechaS',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='metodo_pago',
            new_name='metodo_pagoS',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='subtotal',
            new_name='subtotalS',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='total',
        ),
        migrations.AddField(
            model_name='venta',
            name='totalS',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='total de venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='movimiento_caja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cashiers.movimientocaja', verbose_name='movimiento de cajas'),
        ),
    ]
