# Generated by Django 4.2.6 on 2023-11-17 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_venta_cliente_venta_descuento_venta_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sales.cliente', verbose_name='clientes'),
        ),
    ]
