# Generated by Django 4.2.6 on 2023-11-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_venta_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='dk.erickmontes.coding@gmail.com', max_length=254, verbose_name='Email'),
        ),
    ]
