# Generated by Django 4.2.6 on 2023-11-27 17:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_negocio_direccion_negocio_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
